### ISSUE TITLE
Link wizard is broken in flexform (patch included)

### ISSUE THREAD

**Issue by Simz** [FriendsOfTYPO3/compatibility6#12]
The value of input field is not saved when modified using a link wizard from a flexform.
The TBE_EDITOR_fieldChanged is wrongly set to the parent data structure.
The patch is taken from the typo3 source.

[linkwizard.txt](https://github.com/FriendsOfTYPO3/compatibility6/files/913558/linkwizard.txt)

**Comment by IchHabRecht** [comment]
Hi Simz,

I think this is the same issue as #4, isn't it?

**Comment by IchHabRecht** [comment]
Issue should be solved with merge of #9
