### ISSUE TITLE
Problem with MySQL "strict mode" on page creation

### ISSUE THREAD

**Issue by sypets** [FriendsOfTYPO3/compatibility6#18]
# problem

If "strict mode" is enabled, which is the default case in newer MySQL server versions, an already known and reported problem occurs if a new page is created.

AFAIK all other "strict mode" issues have been eliminated for TYPO3 7.6. This problem only occurs if compatibility6 is installed.

# error message

2: SQL error: 'Incorrect integer value: '' for column 'storage_pid' at row ...'

<pre>
 array(4 items)
   caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_INSERTquery' (60 chars)
   ERROR => 'Incorrect integer value: '' for column 'storage_pid' at row 1' (61 chars)
   lastBuiltQuery => 
'INSERT INTO pages (doktype,hidden,starttime,endtime,layout,url_scheme,urltyp
      e,lastUpdated,newUntil,cache_timeout,shortcut,shortcut_mode,content_from_pid
      ,mount_pid,module,perms_userid,perms_groupid,perms_user,perms_group,perms_ev
      erybody,sorting,pid,title,nav_title,subtitle,nav_hide,extendToSubpages,fe_gr
      oup,fe_login_mode,abstract,keywords,description,author,author_email,backend_
      layout,backend_layout_next_level,alias,target,cache_tags,no_cache,l18n_cfg,i
      s_siteroot,no_search,editlock,php_tree_stop,<b>storage_pid</b>,tsconfig_includes,TS
      config,categories,crdate,cruser_id,tstamp,t3ver_stage) 
VALUES ('1','1','0','
      0','0','0','1','0','0','0','0','0','0','0','','1','0','31','27','0','256','2
      ','start page','','','0','0','','0','','','','','','','','','','','0','0','0','0'
      ,'0','0',<b>''</b>,'','','0','1502554748','1','1502554748','0')' (816 chars)
   
debug_backtrace => '{closure}#21 // TYPO3\CMS\Backend\Http\Application->run#20 // TYPO3\CMS\Core
      \Core\Bootstrap->handleRequest#94 // TYPO3\CMS\Backend\Http\RequestHandler->
      handleRequest#302 // TYPO3\CMS\Backend\Http\RequestHandler->dispatch#95 // T
      YPO3\CMS\Backend\Http\RouteDispatcher->dispatch#168 // call_user_func_array#
      54 // TYPO3\CMS\Backend\Controller\EditDocumentController->mainAction# // TY
      PO3\CMS\Backend\Controller\EditDocumentController->processData#2040 // TYPO3
      \CMS\Core\DataHandling\DataHandler->process_datamap#588 // TYPO3\CMS\Core\Da
      taHandling\DataHandler->insertDB#1336 // TYPO3\CMS\Core\Database\DatabaseCon
      nection->exec_INSERTquery#6829 // TYPO3\CMS\Core\Database\DatabaseConnection
      ->debug#223' (695 chars)
</pre>

# reason

_storage_pid_ is defined as _int_ in _ext_tables.sql. The _INSERT_ statement tries to insert an empty string for this field.

**Comment by IchHabRecht** [comment]
Issue is closed with #19
