### ISSUE TITLE
could you remove the loadTCA method calls?

### ISSUE THREAD

**Issue by robertocabellon** [FriendsOfTYPO3/compatibility6#6]
I installed an old extension "Google Translate" that called the loadTCA deprecated method and turned into unresponsive system.

the compatibility6 extension solved some other incompatibilities but this one still was there...

"t3lib_div::loadTCA was deprecated in TYPO3 6.1. It is now an empty method."
https://github.com/kitodo/kitodo-presentation/pull/30

**Comment by IchHabRecht** [comment]
Hi @robertocabellon,

I'm afraid to tell you that the issue you reported cannot be solved within compatiblity6. This extension provides additional functions for TYPO 7 LTS that were available in 6.2 but not before.

Thanks for your understanding.
